services:
  odoo:
    image: odoo:17.0
    container_name: odoo17
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo 
    environment:
      - HOST=host.docker.internal
      - USER=odoo
      - PASSWORD=odoo
    command: odoo -c /etc/odoo/odoo.conf

